services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    cpus:  1
    mem_limit: 64m
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/html:/usr/share/nginx/html:ro  # 可选
      # Let's Encrypt: ACME challenge folder used by certbot
      - /opt/docker/nginx/certbot/www:/var/www/certbot:rw
      # Let's Encrypt live certs (ensure this is populated by certbot process)
      - /etc/letsencrypt:/etc/letsencrypt:ro
#    depends_on:
#      - java-app
    networks:
      - wp-net

# docker network create wp-net
networks:
  wp-net:
    external: true
    name: wp-net


# test
# curl http://localhost:8090
# docker run -d --name wpadmin90 --hostname wpadmin -p 8090:8090 --network=wp-net wpadmin:latest
